apps/amigo2/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^home/$', views.home, name='home'),
	url(r'^logout/$', views.logout, name="logout"),
	url(r'^user/(?P<user_id>[^/]+)(?:/)*$', views.user, name="user"),
	url(r'^addfriend/(?P<user_id>[^/]+)(?:/)*$', views.addfriend, name="addfriend"),
	url(r'^deletefriend/(?P<user_id>[^/]+)(?:/)*$', views.deletefriend, name="deletefriend"),
]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# urlpatterns = [
#     url(r'^',include('apps.first_app.urls'))
# ]
# urlpatterns = [
#     url(r'^',include('apps.second_app.urls'))
# ]
# urlpatterns = [
#     url(r'^',include('apps.login.urls'))
# ]
urlpatterns = [
    url(r'^',include('apps.travel.urls'))
]

apps/amigo2/models.py
# from __future__ import unicode_literals
# from django.db import models
# from django.core.exceptions import ValidationError
# from django.contrib.auth.models import UserManager
# from .mixins import CustomMixin

# # VALIDATION METHODS
# def validateLengthGreaterThanTwo(value):
# 	if len(value)< 3:
# 		raise ValidationError(
# 			'This field must be longer than 2 characters'.format(value)
# 		)


# class User(CustomMixin, models.Model):
# 	alias = models.CharField(max_length=100, validators = [validateLengthGreaterThanTwo], unique=True)
# 	name = models.CharField(max_length=100, validators = [validateLengthGreaterThanTwo])
# 	email = models.EmailField(max_length=200, unique=True)
# 	password = models.CharField(max_length=255, validators = [validateLengthGreaterThanTwo])
# 	dob = models.DateField()
# 	is_active = models.BooleanField(default=True)
# 	is_admin = models.BooleanField(default=False)
# 	created_at = models.DateTimeField(auto_now_add=True, blank=True)
# 	last_login = models.DateTimeField(auto_now_add=True, blank=True)
# 	friend = models.ManyToManyField("self")

# 	REQUIRED_FIELDS = []
# 	objects = UserManager()
# 	def __str__(self):
# 		return self.email
# 	def __unicode__(self):
# 		return unicode(self.id)
# 	class Meta:
# 		db_table = 'users'

# 	USERNAME_FIELD = 'email'

apps/amigo2/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# Create your views here.
from django.shortcuts import render, redirect, HttpResponse
from .models import User
from .forms import RegistrationForm, LoginForm
from django.contrib.auth import authenticate, login, logout as django_logout
from django.forms.forms import NON_FIELD_ERRORS
from django.contrib import messages

def index(request):
	if not 'id' in request.session:
		request.session['id'] = None
	form1 = LoginForm()
	form2 = RegistrationForm()
	if request.method == 'POST':
		# LOGIN
		if 'login' in request.POST:
			form1 = LoginForm(data=request.POST)			
			if form1.is_valid():
				user = authenticate(username=request.POST['email'], password=request.POST['password'])
				form1.full_clean()
				if user:
					login(request, user)
					request.session['id'] = user.alias
					return redirect('/home')
				form1._errors[NON_FIELD_ERRORS] = form1.error_class(['User does not exist or incorrect password.'])
		# REGISTER
		if 'register' in request.POST:
			form2 = RegistrationForm(data=request.POST)
			if form2.is_valid():
				form2.save()
				user = User.objects.get(email=request.POST['email'])
				request.session['id'] = user.alias
				return redirect('/home')
	return render(request, "index.html", {"form1":form1, "form2":form2})

def home(request):
	if request.session['id'] == None:
		return redirect('/')
	user = User.objects.get(alias=request.session['id'])
	friends = user.friend.all()
	friendslist = []
	for x in friends:
		friendslist.append(x)
	nonfriends = User.objects.all().exclude(alias=user.alias)
	for x in friendslist:
		nonfriends = nonfriends.exclude(alias=x.alias)
	context = {
		'user': request.session['id'],
		'friends': friends,
		'nonfriends': nonfriends,
	}
	return render(request, 'home.html', context)

def logout(request):
	django_logout(request)
	request.session['id'] = None
	return redirect('/')

def user(request, user_id):
	context = {
		'user': User.objects.get(id=user_id)
	}
	return render(request, 'accounts/user.html', context)

def addfriend(request, user_id):
	newfriend = User.objects.get(id=user_id)
	user = User.objects.get(alias=request.session['id'])
	user.friend.add(newfriend)
	user.save()
	newfriend.friend.add(user)
	return redirect('/home')

def deletefriend(request, user_id):
	oldfriend = User.objects.get(id=user_id)
	user = User.objects.get(alias=request.session['id'])
	user.friend.remove(oldfriend)
	user.save()
	oldfriend.friend.remove(user)
	return redirect('/home')

apps/amigo2/templates/form_template.html
{% for error in form.non_field_errors %}
	<p class="error"><strong><i>{{ error }}</i></strong></p>
{% endfor %}



{% for field in form %}


    <div>
        <div>
            {% for error in field.errors %}
                <p class="error"><strong><i>{{ error }}</i></strong></p>
            {% endfor %}
        </div>
        <div class="row">
            <label>{{ field.label_tag }}</label>
            {{ field }}
        </div>
        {% if 'password1' in field.label_tag %}
            <p class='newline'>*Password should be at least 8 characters</p>
        {% endif %}
    </div>
{% endfor %}

apps/amigo2/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Friends</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'accounts/style.css'  %}">
</head>
<body> 
	<div id="homecontainer">
		<a href="{% url 'accounts:logout' %}" class="navbutton">Log Out</a>
			<h1>Welcome {{ user }}</h1>
			<div id="friendscontainer">
			{% if friends %}
				<h3>Here is the list of your friends:</h3>
				<table>
					<tr>
						<th>Alias</th>
						<th>Action</th>
					</tr>
					{% for friend in friends %}
						<tr>
							<td>{{ friend.alias }}</td>
							<td><a href="/user/{{ friend.id }}">View Profile</a> <a href="/deletefriend/{{ friend.id }}">Remove as Friend</a></td>
						</tr>
					{% endfor %}
				</table>
			{% else %}
				<h3>You don't have friends yet.</h3>
			{% endif %}
		</div>

		{% if nonfriends %}
			<h3>Other Users not on your friends list:</h3>
			<table>
				<tr>
					<th>Alias</th>
					<th>Action</th>
				</tr>
				{% for user in nonfriends %}
					<tr>
						<td><a href="/user/{{ user.id }}">{{ user.alias }}</a></td>
						<td><a href="/addfriend/{{user.id}}" class="btn">Add as Friend</a></td>
					</tr>
				{% endfor %}
			</table>
		{% endif %}
	</div>
</body>
</html>

apps/amigo2/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Login/Registration</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'accounts/style.css'  %}">
</head>
<body>
	<div id="indexcontainer">
		<h2>Welcome!</h2>
		<div id="indexformcontainer">
			<div id='registration' class='indexdiv'>
				<h3 class="divtitle">Register</h3>
				{% if messages %}
					<ul class="messages">
					    {% for message in messages %}
					    	{% if 'registration_error' in message.tags %}
							    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
					    	{% endif %}
					    {% endfor %}
					</ul>
				{% endif %}
				<form action="{% url 'accounts:index' %}" method="POST">
					{% csrf_token %}
					<input type="hidden" name="register">
					{% include 'accounts/form_template.html' with form=form2 %}
					<input type="submit" value="register" class="btn">
					<div class="clear"></div>
				</form>
			</div>
			<div id='login' class='indexdiv'>
				<h3 class="divtitle">Log In</h3>
				{% if messages %}
					<ul class="messages">
					    {% for message in messages %}
					    	{% if 'login_error' in message.tags %}
							    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
					    	{% endif %}
					    {% endfor %}
					</ul>
				{% endif %}
				<form action="{% url 'accounts:index' %}" method="POST">
					{% csrf_token %}
					<input type="hidden" name="login">
					{% include 'accounts/form_template.html' with form=form1 %}
					<input type="submit" value="login" class="btn">
					<div class="clear"></div>
				</form>
			</div>
		</div>
	</div>






















</body>
</html>

apps/amigo2/templates/user.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{{ user.alias }}</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'accounts/style.css'  %}">
</head>
<body>
<a href="/logout" class="navbutton">Logout</a>
<a href="{% url 'accounts:home' %}" class="navbutton">Home</a>

<h1>{{ user.alias }}'s Profile</h1>
<h3>Name: {{ user.name }}</h3>
<h3>Email Address: {{ user.email }}</h3>
	
</body>
</html>